"""Shared pytest fixtures for spectraquant-core tests.

Fixture file: tests/fixtures/prices_synthetic_252x50.csv
  Generated by: np.random.default_rng(seed=42)
  Shape: 300 business-day dates ending 2024-12-31 × 50 symbols.

Symbol layout
  SYM000 — monotonic exponential up-trend (50 % total log-return over 300 days).
             compute_momentum returns a large positive value.
  SYM001 — flat constant price 100.0.
             compute_momentum returns ~0.
  SYM002 — flat constant price 50.0.
             std(daily_return) = 0; compute_low_vol returns 0.0 (maximum raw score).
  SYM003–SYM049 — geometric random walks, log-return ~ N(0, 0.015).
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

import pandas as pd
import pytest

_FIXTURE_CSV = Path(__file__).parent / "fixtures" / "prices_synthetic_252x50.csv"

AS_OF_DATE = date(2024, 12, 31)


@pytest.fixture(scope="session")
def prices_fixture() -> pd.DataFrame:
    """Load the pre-committed synthetic price fixture (seed=42)."""
    df = pd.read_csv(_FIXTURE_CSV, index_col="date", parse_dates=True)
    return df


@pytest.fixture
def as_of() -> date:
    """Reference date for all factor tests."""
    return AS_OF_DATE
